export const GET_USERS = "GET_USERS";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_MEMBERSHIP = "GET_MEMBERSHIP";
export const POST_USERS = "POST_USERS";
export const POST_ACTIVITIES = "POST_ACTIVITIES";
